# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='desk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.Desk'),
        ),
    ]
