# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20160919_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=140)),
                ('desk_number', models.CharField(max_length=1)),
            ],
        ),
    ]
